### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MP3DurationError 

### ISSUE THREAD

**Issue by jonahzheng** [agersant/mp3-duration#15]
`use std::path::Path;
use mp3_duration;

fn main() {
	let path = Path::new("/Users/lvzx/rust_prj/guessing_game/target/debug/aaa.mp3");
	let duration = mp3_duration::from_path(path).unwrap();
	assert_eq!(398, duration.as_secs());
	let nanos = duration.subsec_nanos();
    assert!(2 * 100_000_000 < nanos && nanos < 4 * 100_000_000);
}`    

#cargo run
Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/guessing_game /Users/lvzx/rust_prj/guessing_game/target/debug`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MP3DurationError { kind: UnexpectedFrame { header: 858863314 }, offset: 3265717, at_duration: 204.042441328s }', src/main.rs:15:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by agersant** [comment]
This looks like a malformed mp3 file. Note that the error returned by the library still indicates the duration that could be recovered before encountering bad data.

If you think the mp3 is correctly encoded, can you share it so this issue can be reproduced? If possible, it would also be useful to know which software was used to encode the file.

**Comment by jonahzheng** [comment]
thank you replay.

```
Uploads are disabled.
File uploads require push access to this repository.
```
How to share files with you.

**Comment by jonahzheng** [comment]
The MP3 file has been sent to your mailbox.

**Comment by jonahzheng** [comment]
`use std::path::Path;

fn main() {
    let path = Path::new("/Users/lvzx/rust_prj/guessing_game/target/debug/aaa.mp3");
    match mp3_duration::from_path(path) {
        Ok(duration) => {println!("File duration: {:?}", duration)}
        Err(e) => {println!("err: {}", e)}
    }
}`
output:
err: Unexpected frame, header 0x333136D2 at offset 3265717 (0x31D4B5); measured duration up to here: 204.042441328s

**Comment by agersant** [comment]
Thanks. I will take a look during the weekend.

If you are trying to access the measured duration, you can use `e.at_duration`.

**Comment by agersant** [comment]
Thanks for sending the mp3 file. I just took a in-depth look and I can confirm this is a malformed file.

The last chunks of the file are a MPEG frame (starting at offset 0x31D305) and a ID3v1 frame (starting at offset 0x31D490). However, the MPEG frame is truncated and missing its final 23 bytes. Because of this, skipping past the MPEG frame sends the decoder somewhere inside the middle of the ID3v1 frame - which is not a recoverable error.

The good news is, the duration reported by `e.at_duration` is still correct because the error is at the very end of the file.
